# Generated by Django 5.0.1 on 2024-01-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chirper', '0003_chirp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
